# Generated by Django 4.2.7 on 2023-11-19 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                ("elevator_id", models.IntegerField(primary_key=True, serialize=False)),
                ("current_floor", models.IntegerField()),
                ("direction", models.CharField(default="stop", max_length=4)),
                ("door_status", models.CharField(default="closed", max_length=6)),
                ("running", models.BooleanField(default=False)),
                ("operational", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.IntegerField()),
                ("direction", models.CharField(max_length=4)),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator.elevator",
                    ),
                ),
            ],
        ),
    ]
